In [1]:
import pandas as pd
import numpy as np

In [3]:
vis_data = pd.read_csv("train.csv", encoding = 'ISO-8859-1', low_memory = False)

In [6]:
vis_data.columns

Index(['ticket_id', 'agency_name', 'inspector_name', 'violator_name',
       'violation_street_number', 'violation_street_name',
       'violation_zip_code', 'mailing_address_str_number',
       'mailing_address_str_name', 'city', 'state', 'zip_code',
       'non_us_str_code', 'country', 'ticket_issued_date', 'hearing_date',
       'violation_code', 'violation_description', 'disposition', 'fine_amount',
       'admin_fee', 'state_fee', 'late_fee', 'discount_amount',
       'clean_up_cost', 'judgment_amount', 'payment_amount', 'balance_due',
       'payment_date', 'payment_status', 'collection_status',
       'grafitti_status', 'compliance_detail', 'compliance'],
      dtype='object')

In [7]:
vis_data.head(2)

ticket_id                                     agency_name  \
0      22056  Buildings, Safety Engineering & Env Department   
1      27586  Buildings, Safety Engineering & Env Department   

     inspector_name                      violator_name  \
0   Sims, Martinzie  INVESTMENT INC., MIDWEST MORTGAGE   
1  Williams, Darrin           Michigan, Covenant House   

   violation_street_number violation_street_name  violation_zip_code  \
0                   2900.0                 TYLER                 NaN   
1                   4311.0               CENTRAL                 NaN   

   mailing_address_str_number mailing_address_str_name     city  ...  \
0                         3.0                S. WICKER  CHICAGO  ...   
1                      2959.0       Martin Luther King  Detroit  ...   

  clean_up_cost judgment_amount payment_amount balance_due  \
0           0.0           305.0            0.0       305.0   
1           0.0           855.0          780.0        75.0   

          payment_date      payment_status collection_status grafitti_status  \
0                  NaN  NO PAYMENT APPLIED               NaN             NaN   
1  2005-06-02 00:00:00        PAID IN FULL               NaN             NaN   

                          compliance_detail  compliance  
0               non-compliant by no payment         0.0  
1  compliant by late payment within 1 month         1.0  

[2 rows x 34 columns]

In [16]:
vis_data.state.isna().value_counts()

False    250213
True         93
Name: state, dtype: int64

In [17]:
vis_data.state.describe()

count     250213
unique        59
top           MI
freq      228601
Name: state, dtype: object

In [20]:
vis_data.state.describe()[2]

'MI'

In [19]:
vis_data.state.fillna('MI')

0         IL
1         MI
2         MI
3         MI
4         MI
5         CA
6         MI
7         MI
8         MI
9         MI
10        MI
11        MI
12        MI
13        MI
14        MI
15        MI
16        MI
17        MI
18        MI
19        MI
20        MI
21        MI
22        MI
23        MI
24        MI
25        MI
26        MI
27        MI
28        MI
29        MI
          ..
250276    MI
250277    MI
250278    MI
250279    MI
250280    MI
250281    MI
250282    MI
250283    MI
250284    MI
250285    MI
250286    MI
250287    MI
250288    MI
250289    MI
250290    MI
250291    MI
250292    OH
250293    MI
250294    MI
250295    MI
250296    MI
250297    MI
250298    MI
250299    MI
250300    MI
250301    MI
250302    MI
250303    MI
250304    MI
250305    MI
Name: state, Length: 250306, dtype: object

In [22]:
from sklearn.preprocessing import StandardScaler

In [28]:
sd=vis_data.balance_due.values

In [38]:
sdr=sd.reshape(-1, 1)

In [40]:
scaler = StandardScaler()
sc=scaler.fit_transform(sdr)

In [41]:
sc

array([[ 0.13613444],
       [-0.24315767],
       [-0.36683987],
       ...,
       [-0.36683987],
       [-0.36683987],
       [-0.36683987]])

In [42]:
np.min(sc)

-13.147334652567258

In [44]:
np.sqrt(sd)

D:\DataScience\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([17.4642492 ,  8.66025404,  0.        , ...,  0.        ,
        0.        ,  0.        ])

In [46]:
ssd=np.sqrt(vis_data.balance_due[vis_data.balance_due > 0])

In [47]:
np.mean(ssd)

17.011653135633672

In [49]:
np.median(ssd)-np.mean(ssd)

0.4525960609393067

In [50]:
from sklearn.preprocessing import PolynomialFeatures

In [51]:
pf = PolynomialFeatures(3)

In [77]:
poly_features = pf.fit_transform(vis_data[['balance_due', 'discount_amount']])
poly_features

array([[  1., 305.,   0., ...,   0.,   0.,   0.],
       [  1.,  75.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  1.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.],
       [  1.,   0.,   0., ...,   0.,   0.,   0.]])

In [55]:
poly_features.shape

(250306, 10)

In [66]:
a=[]
for n in range(0,10):
    a.append(poly_features[:,n].mean())
arr=np.array(a)    

In [67]:
arr

array([ 1.00000000e+00,  2.22449058e+02,  1.25166796e-01,  4.17195810e+05,
       -9.85531709e+00,  1.17817392e+01,  2.04200098e+09,  1.17924384e+05,
       -1.49564074e+02,  3.07417605e+03])

In [68]:
arr.max()

2042000980.3445697

In [78]:
d=[]
for n in range(0,250306):
    d.append(poly_features[n,:].mean())
arr2=np.array(d)   

In [80]:
arr2.max()

134204139893.1

In [104]:
df=pd.DataFrame.from_dict(d)

In [89]:
df.iloc[4]

0    0.1
Name: 4, dtype: float64

In [82]:
df.head()

0
0  2846595.6
1    42757.6
2        0.1
3        0.1
4        0.1

In [91]:
df[0].max()

134204139893.1

In [94]:
df[df[0]==df[0].max()]

0
12539   1.342041e+11
22570   1.342041e+11
23126   1.342041e+11
24479   1.342041e+11
24843   1.342041e+11
38585   1.342041e+11
40836   1.342041e+11
41132   1.342041e+11
42332   1.342041e+11
42392   1.342041e+11
42507   1.342041e+11
42653   1.342041e+11
42770   1.342041e+11
44795   1.342041e+11
45307   1.342041e+11
49698   1.342041e+11
53371   1.342041e+11
53644   1.342041e+11
56449   1.342041e+11
58385   1.342041e+11
59285   1.342041e+11
68187   1.342041e+11
69734   1.342041e+11
70583   1.342041e+11
70827   1.342041e+11
79971   1.342041e+11
80568   1.342041e+11
81710   1.342041e+11
81823   1.342041e+11
81857   1.342041e+11
...              ...
186439  1.342041e+11
188882  1.342041e+11
189283  1.342041e+11
189531  1.342041e+11
189552  1.342041e+11
189640  1.342041e+11
189719  1.342041e+11
190063  1.342041e+11
190228  1.342041e+11
190269  1.342041e+11
190702  1.342041e+11
190928  1.342041e+11
191485  1.342041e+11
191795  1.342041e+11
193369  1.342041e+11
193611  1.342041e+11
193925  1.342041e+11
195136  1.342041e+11
195247  1.342041e+11
195533  1.342041e+11
196073  1.342041e+11
199623  1.342041e+11
200370  1.342041e+11
201395  1.342041e+11
201547  1.342041e+11
201556  1.342041e+11
201592  1.342041e+11
202255  1.342041e+11
202622  1.342041e+11
203786  1.342041e+11

[187 rows x 1 columns]

In [96]:
dt_issued_date = pd.to_datetime(vis_data.ticket_issued_date)

In [97]:
vis_data['is_weekend'] = dt_issued_date.dt.weekday > 4

In [99]:
len(vis_data[vis_data['is_weekend']==True])

1620

In [103]:
len(vis_data[pd.to_datetime(vis_data.ticket_issued_date).dt.weekday > 4])

1620

Задание 2.13.5 

Загрузите данные train.csv, найдите признак, обозначающий баланс. Уберите пропуски из этого признака и найдите выбросы с помощью межквартильного расстояния. Найдите модуль разницы между минимальным и максимальным выбросом.

In [105]:
rrr=vis_data.balance_due.dropna()

In [106]:
def outliers_iqr(ys):
    quartile_1, quartile_3 = np.percentile(ys, [25, 75])
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    return np.where((ys > upper_bound) | (ys < lower_bound))[0]  #выдает индексы таких признаков

In [107]:
o = outliers_iqr(rrr)

In [108]:
len(o)

9833

In [115]:
q.min()-q.max()

-18780.0

In [114]:
f=[]
for n in o:
    f.append(vis_data.balance_due[n])
q=np.array(f) 