In [1]:
import numpy as np

In [2]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([1.23027931e-311, 1.24611470e-306, 8.90060780e-307, 1.25300124e-152,
       6.52016598e+252])

In [3]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами  

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [10]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 10

array([[3, 1, 5],
       [2, 4, 7],
       [1, 5, 6]])

In [16]:
np.array(range(9)) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [22]:
np.array([i for i in range(11) if i%2]) 

array([1, 3, 5, 7, 9])

Индексирование массивов NumPy

In [23]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

In [55]:
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [60]:
my_array[:, 3]

array([ 4, 13, 48])

In [58]:
my_array[:-1]

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

Упражнения

In [70]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

Задание 1 
Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [40]:
np.shape(big_secret)

(5, 51)

In [65]:
sum=0
for i in range(0,5):
    sum=sum + big_secret[i, 50]
print(sum)

3154.332495807108


Задание 2 
Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [67]:
sum=0
for i in range(0,5):
    sum=sum + big_secret[i , i]
print(sum)

121.37188663699624


Задание 3 
Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [69]:
sum=1
for i in range(1,6):
    sum=sum* big_secret[-i , -i]
print(sum)

341505315559.2347


Особенность индексирования

In [72]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[52,  9,  7, 11, 91, 22],
       [23, 54, 93, 95, 76, 23],
       [82, 59, 68,  8, 37, 56],
       [51, 50,  5, 66, 53, 28]])

In [73]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[93, 95],
       [68,  8]])

In [74]:
my_slice[:] = 0

In [75]:
my_array

array([[52,  9,  7, 11, 91, 22],
       [23, 54,  0,  0, 76, 23],
       [82, 59,  0,  0, 37, 56],
       [51, 50,  5, 66, 53, 28]])

Упражнения
Продолжим работать с массивом big_secret. 
Замените на 1 все элементы, у которых оба индекса нечётные и на -1 все элементы, у которых оба индекса чётные

In [83]:
for i in range(0,51):
    for j in range (0,5):
        if i%2 and j%2:
            big_secret[j , i]=1
        elif i%2==0 and j%2==0:
            big_secret[j , i]=-1

Задание 4 
Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [81]:
sum=0
for i in range(0,5):
    sum=sum + big_secret[i , i]
print(sum)

-1.0


Задание 5 
Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [82]:
sum=0
for i in range(0,5):
    sum=sum + big_secret[i , i]
print(sum)

-1.0


Операции с массивами

In [84]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [ ]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T   #транспонирование

In [ ]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))  #изменение рамерности

In [ ]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten() # преобразование в одномерный

Сравнения и маски

In [86]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[1, 4, 8, 9],
       [1, 9, 9, 4],
       [0, 7, 7, 2]])

In [87]:
my_array<5

array([[ True,  True, False, False],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [88]:
my_array[my_array<5]

array([1, 4, 1, 4, 0, 2])

In [89]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[1, 8],
       [1, 9],
       [0, 7]])

Сортировка двумерных массивов

In [90]:
my_array = np.random.randint(0, 10, (4, 6))

In [91]:
np.sort(my_array, axis=1)

array([[2, 3, 3, 4, 5, 6],
       [0, 1, 3, 3, 4, 8],
       [0, 2, 3, 4, 6, 6],
       [0, 0, 2, 3, 4, 9]])

In [92]:
np.sort(my_array, axis=0)

array([[0, 0, 3, 2, 3, 0],
       [0, 2, 3, 3, 3, 4],
       [1, 4, 4, 3, 4, 6],
       [2, 6, 5, 6, 8, 9]])

Упражнения
Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [96]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [95]:
np.shape(great_secret)

(100, 3)

Задание 2 
Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой:

In [97]:
sum=0
for i in range(0,3):
    sum=sum + np.cos(great_secret[0, i])
print(sum)

0.16006721889793019


Задание 3 
Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [98]:
great_secret[great_secret>50].sum()

5470.0

Задание 4 
Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений:

In [103]:
gs=great_secret.flatten()

In [104]:
gs[150]

7.0710678118654755

Задание 5 
Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой:

In [106]:
gsort=np.sort(great_secret, axis=0)

In [107]:
sum=0
for i in range(0,3):
    sum=sum + gsort[99, i]
print(sum)

115.12148016521353


Математические и статистические операции
Модуль NumPy содержит множество базовых статистических функций, которые помогают описать имеющиеся данные: среднее арифметическое (mean), медиана (median), стандартное отклонение (std), корреляция (corrcoef) и прочие. Давайте посмотрим, как они работают. 
Для изучения функций будем использовать набор данных, содержащих информацию об учениках шестого класса. Данные об учениках в таблице:
ID (номер в журнале)  Рост, см  Масса тела, кг Cредний балл

Создайте массив, содержащий эти данные, и сохраните его под именем students.

In [5]:
students=np.array([1,135,34,4,2,160,43,5,3,163,40,4.3,4,147,44,5,5,138,41,4.7,6,149,54,3.9,7,136,39,4.2,8,154,48,4.9,
9,137,35,3.7,10,165,60,4.6]).reshape((10, 4))

In [6]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [7]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [8]:
median = np.median(students[:,-1])
median

4.449999999999999

In [9]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

Задание 1 
Чему равно медианное значение массы тела школьников?

In [10]:
median_mass= np.median(students[:,-2])
median_mass

42.0

Задание 2 
На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг:

In [11]:
np.mean(students[:,-2])-np.median(students[:,-2])

1.7999999999999972

Задание 3 
Между какой парой признаков в массиве students наблюдается минимальная корреляция?

In [12]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [13]:
corr = np.corrcoef(students[:,1], students[:,3])
corr

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [14]:
corr = np.corrcoef(students[:,2], students[:,3])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

Задание 4 
Используя имеющийся набор данных о школьниках, найдите чему равно стандартное отклонение их средних баллов:

In [16]:
std = np.std(students[:,3])
std

0.4517742799230607

Задание 5 
Посчитайте, чему равна дисперсия значений веса школьников.
Эту величину можно получить двумя способами: математически, используя определение дисперсии и известную функцию в блоке, или самостоятельно найти подходящую функцию модуля NumPy.

In [18]:
np.std(students[:,2])**2

60.36

In [19]:
np.var(students[:,2])

60.36

Задание 5 
Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.

In [31]:
my_array = np.array([[1, 2, 3, 4, 5 ],
                     [6, 7, 8, 9, 10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin=np.sin(my_array)
my_sin.sum()

-0.05812430261413351

Задание 6  
Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

In [32]:
my_sin[1:4,1:4]=1
my_sin.sum()

7.571718421269144

Задание 7  
Преобразуйте первые 4 столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после запятой.

In [52]:
my_sin[:,:4].reshape((10,2))[:,:1].sum()

2.4057172058139544

Подготовка массива к заданиям 8-10
Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [107]:
bigdata=np.array([x**2 for x in range(100,1000) if x%2])

In [55]:
np.median(bigdata)

302501.0

In [57]:
np.std(bigdata)

292095.0301991155

Задание 10 
Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? Введите полученный ответ без изменений и округлений.

In [108]:
np.shape(bigdata)

(450,)

In [84]:
chet=[]
nechet=[]
for i in range(0,450):
    if i%2==0:
        chet.append(1)
        nechet.append(0)
    elif i%2==1:
        chet.append(0)
        nechet.append(1)

In [105]:
mask_chet=np.array([chet], dtype=bool).reshape((450))
mask_nechet=np.array([nechet], dtype=bool).reshape((450))

In [104]:
np.shape(mask_chet)

(450,)

In [106]:
np.corrcoef(bigdata[mask_chet],bigdata[mask_nechet])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])