Допустим, у нас есть $n$ товаров с заданными стоимостями $v_i$ и массой $w_i$. В сумку убирается $С$ кг. Сколько какого товара взять, чтобы сумма всех стоимостей товаров была наибольшей?

In [2]:
values = [4, 2, 1, 7, 3, 6]
weights = [5, 9, 8, 2, 6, 5]
C = 15
n = 6

Сформулируем задачу:
$$\max\sum v_i x_i$$
$$\sum w_i x_i \leq C $$

Как должна выглядеть задача:
$$\min c^T x$$
$$A x \leq b $$

Получается, что $c=-v$, $A=w^T$, $b=(C)$

In [2]:
import numpy as np

In [3]:
c = - np.array(values)
A = np.array(weights)         #shape = (6,)
A = np.expand_dims(A, 0)      #shape = (1,6)
b = np.array([C])

In [4]:
from scipy.optimize import linprog

In [5]:
linprog(c=c, A_ub=A, b_ub=b)

     con: array([], dtype=float64)
     fun: -52.50000000000001
 message: 'Optimization terminated successfully.'
     nit: 2
   slack: array([-1.77635684e-15])
  status: 0
 success: True
       x: array([0. , 0. , 0. , 7.5, 0. , 0. ])

In [6]:
!pip install cvxpy

  Using cached https://files.pythonhosted.org/packages/8c/cf/a5a98f2828a5436f2882a73f21ca37e7b4a3b2482b5930d95161e3ad6453/cvxpy-1.0.24-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/05/89/e1397f4f6e9b14b4bc0f47c6a31c45e6013c4b017c20c115b607241fbf23/osqp-0.5.0-cp37-none-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/b9/3a/59aa93b573a22fda44402383aeddcc2a081c31e61080af3da9d11855c77a/ecos-2.0.7.post1.tar.gz
  Using cached https://files.pythonhosted.org/packages/f2/6e/dbdd778c64c1920ae357a2013ea655d65a1f8b60f397d6e5549e4aafe8ec/scs-2.1.1-2.tar.gz
  Complete output from command D:\DataScience\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vika\\AppData\\Local\\Temp\\pip-install-cc5mu2um\\ecos\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Vika\AppData\Local\Temp\pip-wheel-frfbvtyl --python-tag

  Failed building wheel for ecos
  Failed building wheel for scs
Command "D:\DataScience\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Vika\\AppData\\Local\\Temp\\pip-install-cc5mu2um\\ecos\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Vika\AppData\Local\Temp\pip-record-o2qg69vo\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Vika\AppData\Local\Temp\pip-install-cc5mu2um\ecos\


In [3]:
import cvxpy

ModuleNotFoundError: No module named 'cvxpy'

In [14]:
x = cvxpy.Variable(shape=n, integer = True)

In [15]:
constraint = (A @ x <= b)
total_value = c * x

In [16]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint])

In [17]:
problem.solve()

-138412039.0000002

In [18]:
x.value

array([ 8388608.00000001, -8388608.00000001, -8388608.00000001,
        8388608.00000001,  6990509.00000001,  8388608.00000001])

Теперь положительные $x$

In [19]:
x = cvxpy.Variable(shape=n, integer=True)
constraint = (A @ x <= b)
x_positive = (x >= 0)
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

-49.000000015906025

In [20]:
x.value

array([7.01265807e-10, 7.99333027e-10, 3.58703130e-10, 7.00000000e+00,
       4.67143021e-10, 9.34955115e-10])

Теперь $x = 0$ или $1$

In [21]:
x = cvxpy.Variable(shape=n, boolean=True)
constraint = A @ x <= b
x_positive = x >= 0
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

-17.00000000382157

In [22]:
x.value

array([1.00000000e+00, 2.25474413e-10, 2.07396078e-10, 1.00000000e+00,
       2.24003299e-10, 1.00000000e+00])

Задание 4.5.1 

Cоставьте оптимальный план перевозок со Склада № 1 и Склада № 2 в три торговые центра с учётом тарифов, запасов и потребностей, которые указаны в таблице:
 

Сформулируйте задачу, как задачу линейного программирования, и решите её любым способом (желательно программным). 
В ответ запишите минимальную суммарную стоимость поставки (с точностью до целых): 

In [50]:
c = np.array([2, 5, 3, 7, 7, 6])

In [51]:
A=np.array([[1,1,1,0,0,0],[0,0,0,1,1,1]])

In [52]:
b=np.array([180,220])

In [53]:
Aeq=np.array([[1,0,0,1,0,0],[0,1,0,0,1,0],[0,0,1,0,0,1]])

In [54]:
beq=np.array([110,150,140])

In [57]:
linprog(c,A,b,Aeq,beq)

     con: array([0., 0., 0.])
     fun: 1900.0
 message: 'Optimization terminated successfully.'
     nit: 9
   slack: array([0., 0.])
  status: 0
 success: True
       x: array([110.,   0.,  70.,   0., 150.,  70.])

Задание 4.5.2 

Решите задачу о назначениях

In [39]:
c = np.array([1000, 12, 10, 19, 8,
              12, 1000, 3, 7, 2,
             10, 3, 1000, 6, 20,
             19, 7, 6, 1000, 4,
             8, 2, 20, 4, 1000])
B=np.zeros((5,25))  #условие, что одно одно задание не более, чем одноному исполнителю
B[0][0:5]=[1,1,1,1,1]
B[1][5:10]=[1,1,1,1,1]
B[2][10:15]=[1,1,1,1,1]
B[3][15:20]=[1,1,1,1,1]
B[4][20:25]=[1,1,1,1,1]
b=np.ones((1,5))
Aeq=np.zeros((5,25)  #условие, что один исполнитель точно получает одно задание
Aeq[0][::5]=[1,1,1,1,1]
Aeq[1][1::5]=[1,1,1,1,1]
Aeq[2][2::5]=[1,1,1,1,1]
Aeq[3][3::5]=[1,1,1,1,1]
Aeq[4][4::5]=[1,1,1,1,1]
beq=np.ones((1,5))
linprog(c,B,b,Aeq,beq)

     con: array([0., 0., 0., 0., 0.])
     fun: 32.0
 message: 'Optimization terminated successfully.'
     nit: 22
   slack: array([0., 0., 0., 0., 0.])
  status: 0
 success: True
       x: array([0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0.])

Задание 4.5.3 

Необходимо найти кратчайший маршрут из точки A, который проходит через все другие точки и возвращается в A.

In [ ]:
c = np.array([12, 10, 20, 4, 7, 3, 6, 2, 8, 19])

A=   #условие, что путь замкнутый
b=[9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
             
Aeq=np.ones((10,10))  #условие, что из одного пункта только один раз
beq=np.ones((1,10))
             
linprog(c,B,b,Aeq,beq)

In [7]:
c = np.array([12, 10, 20, 4, 7, 3, 6, 2, 8, 19])

Aeq=np.ones((10,10))  #условие, что из одного пункта только один раз
beq=np.ones((1,10))
             
linprog(c,Aeq,beq)

     con: array([], dtype=float64)
     fun: 0.0
 message: 'Optimization terminated successfully.'
     nit: 11
   slack: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
  status: 0
 success: True
       x: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])